language: elixir
otp_release:
  - 19.2
elixir:
  - 1.3.4
  - 1.4.2
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
before_script:
  - cd apps/ryal_core && mix db.reset && cd ../..
script:
  - mix test
